/*
 * This file is generated by jOOQ.
 */
package com.mgmtp.internship.experiences.model.tables;


import com.mgmtp.internship.experiences.model.tables.tables.Place;
import com.mgmtp.internship.experiences.model.tables.tables.Quote;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PK_PLACE = Indexes0.PK_PLACE;
    public static final Index PK_QUOTE = Indexes0.PK_QUOTE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PK_PLACE = Internal.createIndex("pk_place", Place.PLACE, new OrderField[] { Place.PLACE.ID }, true);
        public static Index PK_QUOTE = Internal.createIndex("pk_quote", Quote.QUOTE, new OrderField[] { Quote.QUOTE.ID }, true);
    }
}
