/*
 * This file is generated by jOOQ.
 */
package com.mgmtp.internship.experiences.model.tables;


import com.mgmtp.internship.experiences.model.tables.tables.Place;
import com.mgmtp.internship.experiences.model.tables.tables.Quote;
import com.mgmtp.internship.experiences.model.tables.tables.records.PlaceRecord;
import com.mgmtp.internship.experiences.model.tables.tables.records.QuoteRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PlaceRecord, Long> IDENTITY_PLACE = Identities0.IDENTITY_PLACE;
    public static final Identity<QuoteRecord, Long> IDENTITY_QUOTE = Identities0.IDENTITY_QUOTE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PlaceRecord> PK_PLACE = UniqueKeys0.PK_PLACE;
    public static final UniqueKey<QuoteRecord> PK_QUOTE = UniqueKeys0.PK_QUOTE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<PlaceRecord, Long> IDENTITY_PLACE = Internal.createIdentity(Place.PLACE, Place.PLACE.ID);
        public static Identity<QuoteRecord, Long> IDENTITY_QUOTE = Internal.createIdentity(Quote.QUOTE, Quote.QUOTE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<PlaceRecord> PK_PLACE = Internal.createUniqueKey(Place.PLACE, "pk_place", Place.PLACE.ID);
        public static final UniqueKey<QuoteRecord> PK_QUOTE = Internal.createUniqueKey(Quote.QUOTE, "pk_quote", Quote.QUOTE.ID);
    }
}
