/*
 * This file is generated by jOOQ.
 */
package com.mgmtp.internship.experiences.model.tables;


import com.mgmtp.internship.experiences.model.tables.tables.Place;
import com.mgmtp.internship.experiences.model.tables.tables.Quote;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * place table
     */
    public static final Place PLACE = com.mgmtp.internship.experiences.model.tables.tables.Place.PLACE;

    /**
     * quote table
     */
    public static final Quote QUOTE = com.mgmtp.internship.experiences.model.tables.tables.Quote.QUOTE;
}
